language: node_js
node_js:
- '0.12'
before_install:
- openssl aes-256-cbc -K $encrypted_b48f58bb6465_key -iv $encrypted_b48f58bb6465_iv -in .travis/ssh_key.enc -out ~/.ssh/id_rsa -d
# Set the permission of the key
- chmod 600 ~/.ssh/id_rsa
# Start SSH agent
- eval $(ssh-agent)
# Add the private key to the system
- ssh-add ~/.ssh/id_rsa
# Copy SSH config
- cp .travis/ssh_config ~/.ssh/config
- git config --global user.name "metavige"
- git config --global user.email metavige@gmail.com
- git config --global push.default simple
- npm install hexo-cli -g
- git clone https://github.com/metavige/metavige.github.io.git .deploy_git
script:
- hexo generat --deploy
branches:
  only:
  - master
