language: node_js

sudo: false

branches:
  only:
    - master

cache:
  - npm

node_js:
  - "lts/*"

before_script:
  - npm install
  - hexo cl

script:
  - hexo generate

deploy:
  provider: pages
	skip-cleanup: true
	repo: metavige/metavige.github.io
  github-token: $GITHUB_TOKEN
  local-dir: public
  keep-history: false
  on:
    branch: master
