title: '@metavige'
subtitle: 生命會自己找到出路，程式 Bug 不會自己修復，孩子～
description: null
author: metavige (Ricky Chiang)
language: zh-TW
timezone: null
sitemap:
  path: sitemap.xml
url: 'https://metavige.github.io'
root: /
permalink: ':year/:month/:day/:title/'
permalink_defaults: null
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: ':lang'
skip_render: null
new_post_name: ':title.md'
default_layout: post
auto_spacing: true
titlecase: false
external_link: true
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  backtick_code_block: true
  tab_replace: null
default_category: uncategorized
category_map: null
tag_map: null
archive: 1
category: 1
tag: 1
date_format: YYYY-MM-DD
time_format: 'HH:mm:ss'
per_page: 5
pagination_dir: page
theme: light
deploy:
  type: git
  repo: 'git@github.com:metavige/metavige.github.io.git'
marked:
  gfm: true
  pedantic: false
  sanitize: false
  tables: false
  breaks: false
  smartLists: false
  smartypants: false
feed:
  type: atom
  path: atom.xml
  limit: 20
disqus_shortname: metavigegitpages
livereload:
  port: 35729
