menu:
  Home: /
  Archives: /archives
  RSS: /atom.xml

widgets:
- search
- category
- tag
- tagcloud

excerpt_link: 還有...

twitter:
  username: metavige
  show_replies: false
  tweet_count: 5

addthis:
  enable: true
  facebook: true
  twitter: true
  google: true
  pinterest: false

fancybox: true

google_analytics:
rss: true

comment_provider: 

# Facebook comment
facebook:
  appid: 1585737331664537
  comment_count: 5
  comment_width: 840
  comment_colorscheme: light
