menu:
  Home: /
  Archives: /archives

widgets:
- search
- category
- tag

excerpt_link: 閱讀全文

twitter:
  username: metavige
  show_replies: false
  tweet_count: 5

addthis:
  enable: true
  facebook: true
  twitter: true
  google: true
  pinterest: true

fancybox: true

google_analytics:
rss: true

comment_provider: facebook

# Facebook comment
facebook:
  appid: 1585737331664537
  comment_count: 5
  comment_width: 840
  comment_colorscheme: light
