name: GitHub Actions Build and Deploy
on:
  push:
    branches:
      - pages-src
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Build and Deploy
        uses: JamesIves/github-pages-deploy-action@master
        env:
          GITHUB_PAGE: true
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKENS }}
          BASE_BRANCH: pages-src
          BRANCH: master
          FOLDER: public
          BUILD_SCRIPT: npm install && npm run generate
