name: GitHub Actions Build and Deploy
on:
  push:
    branches:
      - pages-src
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build
        run: npm install && npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        env:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKENS }}
          BASE_BRANCH: pages-src
          BRANCH: master
          FOLDER: public
